freeCodeCamp/testable-projects-fcc

- src/project-tests/bar-chart-tests.js
- src/project-tests/calculator-tests.js
- src/project-tests/choropleth-tests.js
- src/project-tests/drum-machine-tests.js
- src/project-tests/heat-map-tests.js
- src/project-tests/markdown-previewer-tests.js
- src/project-tests/pomodoro-clock-tests.js
- src/project-tests/product-landing-page-tests.js
- src/project-tests/scatter-plot-tests.js
- src/project-tests/technical-docs-tests.js
Reverts freeCodeCamp/testable-projects-fcc#12
> Revert "Fix typos, add Main element in Tech Docs"

- build/bundle.js
- src/project-tests/bar-chart-tests.js
- src/project-tests/calculator-tests.js
- src/project-tests/choropleth-tests.js
- src/project-tests/drum-machine-tests.js
- src/project-tests/heat-map-tests.js
- src/project-tests/markdown-previewer-tests.js
- src/project-tests/pomodoro-clock-tests.js
- src/project-tests/product-landing-page-tests.js
- src/project-tests/scatter-plot-tests.js
- src/project-tests/technical-docs-tests.js
Here's the amended PR after running `npm run build`  - hopefully good to go!
> Fix typos, add Main element in Tech Docs

- build/bundle.js
- src/project-tests/tribute-page-tests.js
> fix(tests): tribute page 4, 5, layout 2

- build/bundle.js
- src/project-tests/markdown-previewer-tests.js
- Fixes assertion error messages as described in issue #37
> fix(tests): typos in markdown assertion errors, test 6

- CONTRIBUTING.md
- build/bundle.js
- src/project-tests/tribute-page-tests.js
- Fixes Typos as described in issue #39 
- Fixes Typos in CONTRIBUTING.md which were found while working on above
> fix(various): typos in tribute page tests, test 6 and in CONTRIBUTING.md

- build/bundle.js
- local_test/index.html
- src/project-tests/survey-form-tests.js
removed erroneous checks for active checks and radio buttons
required more than one radio, checkbox and option
This may break past solutions to the challenge. Since we are not in production with these, no big deal. The user stories have also changed, so anyone that goes back to check can see what's changed and fix their project accordingly. This will only affect people who did the absolute bare minimum just to help us QA anyway. 
This PR fixes some non-sense that I have no idea why was there in the first place (although it's likely I'm the one who put it there)
> fix(tests): survey form

- build/bundle.js
- local_test/index.html
- src/project-tests/pomodoro-clock-tests.js
- added additional errors that are thrown in place of non-descriptive timeout errors
- added time hack to beforeEach hook to improve speed
- added function that runs timer before all tests to avoid common camper error
- also add `new Error()` to promise `reject()`s so that errors are displayed cleaner
This _**may**_ break some past solutions if campers did not handle timer label correctly
> pomodoro suite timeout error fixes

- build/bundle.js
- src/project-tests/quote-machine-tests.js
Changes the upper value for delta in function testHorizontallyCentered to 8.6
Adds a note to reset the browser's zoom level to 100%.
> changes delta value, adds note about zoom level

- .github/ISSUE_TEMPLATE.md
- build/bundle.js
- src/project-tests/bar-chart-tests.js
- src/project-tests/drum-machine-tests.js
- src/project-tests/quote-machine-tests.js
- src/project-tests/scatter-plot-tests.js
Closes #51 
- fixed drum machine tests to properly target innerText of nested elements
- added new Error() to reject messages throughout the entire project for cleaner errors
- updated issue template so campers no to include links to their pens
> fix(tests): drum machine, throwing errors better

- build/bundle.js
- src/project-tests/tribute-page-tests.js
May close issue #49 
increased delta for second layout test yet again to 11 instead of 10 --- at some browser widths test fails but is always off by 11 px, current delta allows 10px variance. Hoping this will finally fix it.
> fix(tests): tribute page, delta of last test

- build/bundle.js
- src/assets/globalD3Tests.js
- src/index.js
- src/project-tests/bar-chart-tests.js
- src/project-tests/choropleth-tests.js
- src/project-tests/drum-machine-tests.js
- src/project-tests/heat-map-tests.js
- src/project-tests/pomodoro-clock-tests.js
- src/project-tests/scatter-plot-tests.js
- src/project-tests/tree-map-tests.js
- fixed cross browser issues - thanks @christophherr! 
- the issue was assigning a new value to a classList DOMToken in the index file. This is not allowed in strict mode in browsers other than chrome. Wrote a short function to iterate through the list and remove each class manually to reset button classes instead.
- added alert for remaining small issue, `.paused()` web media api has no (questionable?) support in safari or opera, so last pomodoro test  and some drum machine test will fail in those browsers. 
- better code org, global D3 tests module
> fix(cross browser compatibility issues)

- build/bundle.js
- src/index.js
- src/project-tests/drum-machine-tests.js
- src/project-tests/pomodoro-clock-tests.js
- polyfill addition for iterating over NodeLists with forEach
- into alert so users are aware of cross browser issues
- added specific alert to drum machine suite
This fixes part of #65, but some tests still failing in Safari
> fix(various): polyfill for forEach (NodeLists) & global alert 

- build/bundle.js
- src/project-tests/tree-map-tests.js
remove treemap legend item test, and make legend item color test check all legend children instead of class='legend-item'
> fix(tests): treemap, improve legend-items color test

- build/bundle.js
- src/assets/globalD3Tests.js
- src/project-tests/bar-chart-tests.js
- src/project-tests/choropleth-tests.js
- src/project-tests/heat-map-tests.js
- src/project-tests/scatter-plot-tests.js
- src/project-tests/tree-map-tests.js
- Moved tooltip tests to global D3 tests
- All tests verified to pass on the following browsers
- Chrome 56.0.2924.87
- Firefox 51.0.1
- Edge 25.10587.0.0
- Safari 10.0
- Note:  All D3 Tests still fail on Internet Explorer 11.0.9600.18163 because of the lack of support for Promises
> Fixed failing d3 tests due to crossbrowser issues

- CONTRIBUTING.md
Changed awseomness to awesomeness
> Fix typo in CONTRIBUTING doc

- build/bundle.js
- src/project-tests/pomodoro-clock-tests.js
I inadvertently broke this suite last time I worked on it by causing a type error by creating a reference to an element that does not exist yet when the suite is initialized. Used `&&` to account for this, shouldn't affect the suite otherwise. 
Also, caught another error where good ol `&&` came in handy in the `before` hook for this suite. Working well locally now.
> fix initial state of pomodoro so suite will run

- build/bundle.js
- src/project-tests/product-landing-page-tests.js
Navbar layout test now checks the position of the header element and its children, to determine if any of them are consistently at the top of the page. This was implemented to accommodate the way bootstrap and other libraries handle sticky-navbars.
> fix(tests): product landing page, improve navbar position test

- build/bundle.js
- src/project-tests/calculator-tests.js
Thanks again @felixmuecke. By the time you see this, it is likely that your calc will no longer pass all the tests 😄  Changes are being deployed now
> fix(tests): improve test stringency

- build/bundle.js
No code was changed. I just ran the build process after running `npm install`, which results in a newer version of jquery being used for the bundle. Every sample project was tested to make sure the new version of jquery doesn't break anything.
> bundle.js using the latest version of jquery and webpack per package.json versions.

- build/bundle.js
- src/project-tests/survey-form-tests.js
My apologies. I ran the FCC codepen through the tests and didn't also run tests on the datalist tag itself! Please accept my apologies. This passes with a datalist with exclusive id='dropdown'.
> remove camelcase on dropDown var

- build/bundle.js
- src/project-tests/technical-docs-tests.js
- Added a test to make sure the navbar header comes before the links.
- Added chai assert messages to make is clearer where the layout tests fail.
- Note there are some whitespace changes to remove trailing whitespaces.
The navbar section can now include containers outside the header element and the tests will still pass, making the tests less brittle. Also added some Chai messages to make it clearer where tests fail.
> Made the test for the navbar header element less brittle. See other changes below.

- build/bundle.js
- src/project-tests/tribute-page-tests.js
This simplifies the test for checking centering of img element within parent element. Also should work in all browsers.
> use getBoundingClientRect for determining img centering

- src/assets/test_suite_skeleton.js
- src/index.js
- src/project-tests/bar-chart-tests.js
- src/project-tests/calculator-tests.js
- src/project-tests/choropleth-tests.js
- src/project-tests/drum-machine-tests.js
- src/project-tests/heat-map-tests.js
- src/project-tests/markdown-previewer-tests.js
- src/project-tests/pomodoro-clock-tests.js
- src/project-tests/portfolio-tests.js
- src/project-tests/product-landing-page-tests.js
- src/project-tests/quote-machine-tests.js
- src/project-tests/scatter-plot-tests.js
- src/project-tests/survey-form-tests.js
- src/project-tests/technical-docs-tests.js
- src/project-tests/tree-map-tests.js
- src/project-tests/tribute-page-tests.js
@tchaffee @tbushman this is a re-do of #123 - same exact thing but includes latest changes. Since there are no actual changes to the code, just the spacing/style, I didn't add these changes to the build because that's what made the merge conflicts in the last try hard to fix. 
I think we should prob merge this in ahead of anythigng else to avoid a repeat, but since not added to the build if we do merge something else in first and see conflicts, that should make it easier to fix. 
From here on out, now that spacing is fixed, we can do one or two files at a time to match the bar chart and calc code style
> fix all indentations and quotes and max-length for calc and bar chart

- build/bundle.js
The indentation changes to the other files were not included in bundle.js, and that is making new PRs messy, because they do include *all* the indentation changes in bundle.js.
> Built the bundle.js using the new indentation.

- build/bundle.js
- src/assets/alignmentD3Tests.js
- src/project-tests/scatter-plot-tests.js
This new PR gives a 1px leeway on checking alignment to account for 0.5px offset on d3 axes and apparent difference in codepen's window and the regular window tests.
> account for 0.5px axis width subtracted from each end of d3 axis

- build/bundle.js
- src/project-tests/quote-machine-tests.js
This PR updates tests 5 and 10 in quote-machine tests to specify that an anchor element is required to use for the tweeting quotes.    Tested these changes against [example project](https://codepen.io/freeCodeCamp/pen/qRZeGZ).  
**Note** The example project fails test 10 from existing test suite code **(before my PR)** when test are run locally, because it uses a click handler/openURL instead of href.   It passes all tests when test suite is run on Codepen because it adds the href when in codepen's iFrame.   
I have a simpler [pen example](https://codepen.io/marigerr/pen/KNQexq) that passes both versions of tests (before and after my PR) when run locally and on Codepen.   Here is a rawgit link of the bundle for this PR.  
https://rawgit.com/marigerr/testable-projects-fcc/fix/quote-machine- …
> Fix quote-machine. Tests 5 & 10 - Specify need to use anchor element

- build/bundle.js
- src/project-tests/quote-machine-tests.js
check element's placement in relation to viewport instead of relation to parent element
Changed layout test to use `getBoundingClientRect()` instead of `offsetLeft` to calculate elements placement in relation to viewport instead of parent element.   This change will allow Bootstrap offset class to be used to center element on page.    
In case scrollbar is present, allow 20px difference between right and left gap.   
Rawgit link  
https://rawgit.com/marigerr/testable-projects-fcc/fix/quote-machine-layout-test/build/bundle.js
> check element's placement in relation to viewport 

- build/bundle.js
- src/project-tests/heat-map-tests.js
- src/project-tests/scatter-plot-tests.js
Preparing to submit a PR to accommodate heat map in the d3 alignment tests. This addresses eslint formatting for affected files.
> eslint formatting for heat map and scatter-plot

- .gitignore
- .travis.yml
- CONTRIBUTING.md
- README.md
- config/live-server-https.js.example
- package.json
- test/automate/automate-utils.js
- test/codepen-projects.js
- test/mocha.opts
- test/screenshots/.gitignore
- test/setup.js.example
- test/setup.js.travis
- Uses Selenium to automate using the browser to run the tests for every CodePen.
- Use "npm run live-serve-build" to serve up your local version of bundle.js.
- The mocha.opts file tells the tests what URL to use for bundle.js.
- Use "npm test" command to run all the tests.
Please do NOT merge this. There is a little more work to do, but I want to put the PR up to give more time to start the code review as most of the code will not be changed. Please test locally.
- Uses Selenium to automate using the browser to run the tests for every CodePen.
- You will need to create a server.crt and server.key file in the config directory. And then move `live-server-https.js.example` to `live-server-https.js` and change the password.
- The mocha.opts file tells the tests what URL to use for …
> Automate testing of all the CodePen Project tests.

- build/bundle.js
- src/assets/alignmentD3Tests.js
- src/project-tests/heat-map-tests.js
- src/project-tests/scatter-plot-tests.js
Changed alignmentD3Tests.js to accommodate rect and months. Changes necessitated changing scatter-plot-tests.js as well.
> D3 alignment tests accommodating heat map

- CONTRIBUTING.md
- README.md
Just made some minor fixes to the docs. No local testing required. Should be a very quick review and merge.
> Minor fixes to the automated testing docs.

- build/bundle.js
- src/project-tests/tribute-page-tests.js
Just fixed the formatting of the Tribute Page tests to pass the ESLint tests. This is in preparation for making actual changes to the file to improve the test wording and making sure the tests do what they say.
> Fixed formatting to pass ESLint rules.

- CONTRIBUTING.md
Just some very small documentation fixes. Can be safely merged.
> Small fixes to the automated testing docs.

- build/bundle.js
- src/project-tests/tribute-page-tests.js
Reviewed all the tests for the Tribute page. Made one of them more accurate by adding assertions. These tests now look good to me and we can call this test suite complete for now.
> Made the Tribute page tests more accurate.

- build/bundle.js
- src/project-tests/survey-form-tests.js
Formating changes only to fix ESLint warnings. This can safely be merged without code review.
> Fixed the ESLint formatting errors in prep for making actual changes.

- build/bundle.js
- src/project-tests/product-landing-page-tests.js
This is only a formatting change to fix ESLint warnings, in preparation for making more substantial changes to this file. Review if you like, but this can be safely merged without review.
> Fixed ESLint warnings for Product Landing Page tests.

- build/bundle.js
- src/project-tests/survey-form-tests.js
Improved the log of test 14, so please pay extra attention to the changes there.
All the other changes should just be changes to the test text to more accurately describe what is actually being tested.
> Mostly changes to the test text to make them more accurate.

- build/bundle.js
- src/assets/sharedTestStrings.js
- src/assets/styleSheetUtils.js
- src/assets/test_suite_skeleton.js
- src/project-tests/product-landing-page-tests.js
- Added a technology stack requirement. No testing - it automatically passes. This can be reused in other projects from the same section. I will add text for other sections later.
- Tried to improving the phrasing of requirements where needed.
- Improved the layout tests by replacing "for loops" and repeated code with new filtering friendly functions in their own module.
- Improved the layout tests by filtering our test suite styles from the tests and doing the filtering in a generic way that should accommodate future styles being added to our test suite UI. This is much more reliable than the previous method of counting.
- Updated the test suite UI code to warn about how styles must be named to support the filtering.
> Product Landing Page test improvements

- build/bundle.js
- src/project-tests/technical-docs-tests.js
Only made changes to pass ESLint in preparation for functional changes.
> Formatting changes to Technical Docs Tests to pass ESLint

- build/bundle.js
- src/project-tests/technical-docs-tests.js
- Added the tech stack requirement "test".
- Fixed a couple of formatting problems I missed the first time around.
- Use filtering instead of "for loop" to detect use of media query.
> Fixes to the Technical Docs project tests.

- build/bundle.js
- src/project-tests/portfolio-tests.js
Only formatting changes to fix ESLint warnings. In prep for functional changes.
> Portfolio Page Tests - formatting changes to fix ESLint warnings.

- build/bundle.js
- src/project-tests/quote-machine-tests.js
Formatting changes to Quote Machine tests to fix ESLint warnings.
> Formatting changes to Quote Machine tests to fix ESLint warnings.

- build/bundle.js
- src/project-tests/portfolio-tests.js
- Added the tech stack requirement.
- We don't need to use FCC_Global if we import chai. With this small change there are now zero ESLint warnings in this file.
- Changed the numbering of the tests to be dynamic. This allows more easily adding new tests without having to edit the numbers. It also justifies using string template literals (interpolated string literals).
- Replaced 'for loop' logic with safer Array.prototype.some() logic for the navbar scrolling tests.
- Replaced 'for loop' logic with safer filtering to detect media queries.
> Minor fixes to the Portfolio tests

- build/bundle.js
- src/assets/sharedTestStrings.js
- src/project-tests/tribute-page-tests.js
Added the tech stack requirement and eliminated all ESLint warnings. The hope is that these are the final changes to this file for this phase of the project.
> Tribute Page: added the tech stack requirement and eliminated all ESLint warnings.

- build/bundle.js
- src/project-tests/survey-form-tests.js
- Removed functions that can be substituted with simpler querySelectorAll.
- Added the tech stack requirement.
- Replaced 'for loops' with functional equivalants.
- Removed FCC_Global and import 'assert' instead.
- Use 'const' and 'let' instead of var when appropriate.
> Survey Form: eliminate all ESLint warnings, along with some refactoring.

- build/bundle.js
- src/project-tests/product-landing-page-tests.js
- Replaced hard coded test numbering with dynamic numbering.
- Moved the tech requirements to its own section.
- Removed FCC_Global and import 'chai assert' instead.
> Product Landing: fixed remaining ESLint warnings and other small improvements

- build/bundle.js
- src/project-tests/markdown-previewer-tests.js
Fixed ESLint warnings. In prep for further improvements.
> Markdown Previewer: fixed ESLint warnings.

- build/bundle.js
- src/project-tests/technical-docs-tests.js
- Increment test numbers instead of hard coding them.
- Moved the Tech Stack requirements to their own section.
- Get rid of FCC_Global by importing 'chai assert' instead.
> Technical Docs Tests: fix ESLint warnings and other small improvements.

- build/bundle.js
- src/assets/elementUtils.js
- src/assets/sharedTestStrings.js
- src/project-tests/quote-machine-tests.js
- Moved the centering test to its own module. Hopefully it can be reused.
- Added the Technology Stack requirement.
- Added dynamic test numbering.
- Changed the timeout logic so the tests pass immediately when success is detected. This way is more deterministic and should eliminate the occasional failures we get with this test suite. In addition, the tests are now significantly faster.
- Used Promises everywhere applicable, instead of a mix of promises and 'done'.
> Quote Machine: Small Improvements listed in the commit body.

- build/bundle.js
- src/project-tests/pomodoro-clock-tests.js
This has no more eslint errors. Added observer.disconnect() in new `else if` blocks. Removed unused parameters.
> wip pomodoro eslint

- build/bundle.js
- src/project-tests/markdown-previewer-tests.js
- Added inline documentation where needed.
- Moved variable declarations to the top of functions.
- Implemented the OPTIONAL BONUS test for rendering <br> elements.
> Markdown previewer: Small fixes and improvements

- build/bundle.js
- src/project-tests/drum-machine-tests.js
Just fixed ESLint warnings. In prep for any possible improvements to the logic.
> Drum Machine tests: Fixed ESLint warnings.

- build/bundle.js
- src/project-tests/scatter-plot-tests.js
Just fixed any remaining ESLint warnings.
> Scatter Plot tests: fix ESLint warnings.

- build/bundle.js
- src/project-tests/bar-chart-tests.js
Just fixed any remaining ESLint warnings.
> Bar Chart tests: Fixed any remaining ESLint warnings

- build/bundle.js
- src/project-tests/heat-map-tests.js
Fixed remaining ESLint warnings.
> Heatmap tests: fixed remaining ESLint warnings.

- build/bundle.js
- src/project-tests/choropleth-tests.js
> Choropleth tests: fixed ESLint warnings.

- build/bundle.js
- src/project-tests/tree-map-tests.js
> D3 Treemap: fixed ESLint warnings.

- build/bundle.js
- src/project-tests/calculator-tests.js
Basic eslint warning suppression and formatting per discussions.
> formatting changes prior to changes

- build/bundle.js
Rebuild bundle.js to fix __webpack_require__ error. Not sure what was wrong with the bundle, but a rebuild seems to have fixed it.
> Rebuild bundle.js to fix __webpack_require__ error.

- build/bundle.js
- src/assets/alignmentD3Tests.js
Eslint warning suppression only.
> eslint warning suppression for alignmentD3tests module

- build/bundle.js
- src/project-tests/pomodoro-clock-tests.js
- The clickButtonsById function was trying to execute the `click()` method without first checking if the element was valid and has that method.
- Look like ESLint also made some fixes upon save. ;-)
> Pomodoro Clock tests: fixed the clickButtonsById function.

- build/bundle.js
- src/assets/test-suite-skeleton.js
- src/index.js
Just fixed ESLint warnings in index.js. Also had to make a small change to the test-suite-skeleton.js file.
> index.js: fixed ESLint warnings.

- build/bundle.js
- src/index.js
Allows the use of projectName variable for CodePen projects. The existing `project_name` variable will also still work, providing a way for CodePen maintainers to fix the variable name when they find time.
> Index.js: allow the use of projectName variable for CodePen projects.

- build/bundle.js
- src/project-tests/product-landing-page-tests.js
See issue #227. This PR adds assertion for the length of the .nav-link nodelist so the test fails when it should.
> assert #nav-bar .nav-link nodeList is not empty

- package.json
- webpack.config.dev.js
- webpack.config.js
no change to build
Babel now recommends using babel-preset-env instead of
bable-preset-es2015.
Removed babel-preset-es2015
Added babel-preset-env
> Fix Babel Warning Message

- build/bundle.js
- src/project-tests/markdown-previewer-tests.js
With this fix, the fCC Markdown Previewer Codepen may be updated to run React@15.6. It allows the textarea Object to be writable.  
Based on the solution posted here: https://github.com/facebook/react/issues/10135.  
This does not yet solve issue #222, which will require further investigation.
> Fix for latest react version and textarea Object writability

- build/bundle.js
- src/index.js
Now that all of the CodePens have been updated to use the projectName variable, I have removed the older project_name variable. This is one more step in the direction of passing all eslint tests.
> Removed project_name variable from index.js

- build/bundle.js
- src/index.js
index.js was getting a couple of eslint warnings due to the new code for importing a CSS file. I just added eslint directives to make sure the code passes eslint.
> A couple of very minor changes to suppress eslint warnings.

- build/bundle.js
- src/project-tests/markdown-previewer-tests.js
Recent new code for the markdown previewer tests gave some eslint warnings which are fixed with this PR. Once this is merged, all eslint warnings should be gone! At that point I'll create a new PR to add the eslint stuff permanently to this project, which will be a big milestone for us.
> Fixed the remaining eslint warnings for the markdown previewer tests.

- build/bundle.js
- test/alignment-D3.js
There was an unused variable in test/alignment-D3.js
> Fixed ESLint errors for test/alignment-D3.js

- test/setup.js.travis
Oops! The setup.js.travis file has an ESLint problem. Not detected locally because the file does not end in .js until it is copied during the Travis CI setup.
> Fixed setup.js.travis ESLint error

- .eslintrc
- build/bundle.js
- package.json
- File .eslintrc has the rules. These were just copied from the freeCodeCamp main project.
- Updated package.json with the packages needed by ESLint.
- Added a "pretest" script item to package.json. This will automatically be executed before any tests, which means Travis CI will also do the same.
> Added ESLint rules

- build/bundle.js
- src/project-tests/heat-map-tests.js
replaced with a forEach for data-month and data-year, then using
`assert.isAtLeast()` and `assert.isAtMost()` to check values. Thus
ensuring that only numerical values are considered.
> fix(project-test): heatmap not detecting wrong values

- build/bundle.js
- src/project-tests/calculator-tests.js
- src/utils/shared-test-strings.js
- Added the tech stack requirement.
- Make sure all test text accurately reflects the actual tests performed.
> Calculator tests: minor code and text cleanup

- package.json
> chromedriver update

- build/bundle.js
- src/project-tests/pomodoro-clock-tests.js
I have had the opportunity to test these tests. They all pass in Codepen. The last Audio test (3) fails when tested outside of Codepen. If this is a reproducible issue, let me know.
> Pomodoro Tech stack requirement and other categories

- build/bundle.js
- src/project-tests/scatter-plot-tests.js
- src/utils/shared-test-strings.js
Tech stack for D3 projects written and added to Scatter plot tests.
> Scatter plot tech stack

- build/bundle.js
- src/project-tests/choropleth-tests.js
- src/utils/shared-test-strings.js
Checked the tests. Added the tech-stack message -- modified from the main d3ProjectStack message to remove axis language. One suggestion for the Choropleth project would involve changing the path for the project data to point to `testable-projects-fcc/src/data/choropleth_map`, which would require coordination with the beta site:
> tech stack no-axes

- test/automate/automate-utils.js
- Give the example projects time to load data. This is especially needed for the D3 projects which load remote data via XHR. This is a temporary fix that will help the automated tests pass more reliably.
- Codepen changed the class for the "External Scripts/Pens" input. Fixed this to use the correct class.
- Note this does not affect `bundle.js`. The automated tests are not part of the bundle.
> fix: automated test timing problems

- build/bundle.js
- src/project-tests/tree-map-tests.js
- src/utils/element-utils.js
- Added tech stack requirements for D3 Treemap tests.
- Created new function hasUniqueColorsCount to eliminate duplicate code.
- Refactored all the D3 Treemap tests to make sure the wording and code is accurate. Also fixed some bugs, especially regarding the test about the area of the tile reflecting the data values. That test was not even working and would always pass even if the tile sizes were wrong.
> fix: Treemap tests tech stack requirements and refactoring

- build/bundle.js
- src/project-tests/choropleth-tests.js
- src/utils/element-utils.js
> choropleth use utils/hasUniqueColorsCount

- build/bundle.js
- src/project-tests/heat-map-tests.js
- Added the tech stack description.
- Reviewed each test to make sure the wording is right and that the tests work.
- General refactoring for things like eliminating duplicate code and to use safer loop constructs.
- Replace code with hasUniqueColorsCount function.
- Added inline documentation as needed.
> fix: Heatmap tests.

- .travis.yml
- test/setup.js.travis
- travis-screenshots/README.md
This is just a small change to the Travis CI setup so that the screenshots created during the testing are pushed back to github so we can look at them. Screenshots will be sent to branch `travis-screenshots`, which is an empty branch.
> fix: deploy Travis CI screenshots to travis-screenshots branch

- build/bundle.js
- src/project-tests/bar-chart-tests.js
- src/utils/alignment-D3-support.js
- test/alignment-D3-support.js
- test/alignment-D3.js
In the process of integrating the alignment tests with the Bar Chart tests, we have detected misalignment in the Bar Chart codepen. This PR accommodates the misalignment (at most 6px) for now. We will need to update the Bar Chart alignment support function once the chart itself is fixed. 
UPDATE: Even though this code runs fine under local_test, it fails in Codepen. 
UPDATE: Codepen tests working with 5.5px added to axis tick / shape position comparison. This is a stop-gap fix and may cause student pens to fail.
> bar chart alignment y-axis

- .travis.yml
The other approach to capture screen shots (using Travis CI deploy) was not working because deploy is only triggered after a successful build. This PR fixes that by using a custom screen for the `after_failure` Travis CI stage. After a failed build, files will be pushed to the `travis-screenshots` branch of this repo.
> fix: Travis CI send screenshots to github on failed build

- README.md
I made this PR through the github UI, so it doesn't follow some of the guidelines here, but just an update to README.md, so should be ok. Though I'm sure very few people are looking at this (for now anyway), I just wanted to add @tchaffee & @tbushman to the __Credits__ section of the README to acknowledge your countless contributions. Thanks guys for taking this the rest of the way! Really looking forward to seeing how this all goes once we're live come Christmas!
> update credits in README.md

- build/bundle.js
- src/project-tests/markdown-previewer-tests.js
Updated regexp to allow string representing a list item to begin with either minus sign, plus sign or an asterisk. Previously, only minus sign was allowed.
> Fixed li issue in regexp for Markdown Previewer

- build/bundle.js
- package.json
- src/utils/style-sheet-utils.js
- test/automate/automate-utils.js
The npm package for serve-https is currently broken due to some internal issues they are having with servers being down. In the meantime they recommend we use their github repo for the package. 
- Changed package.json to follow their recommendation. If they fix this soon we can revert to using the npm package, and if not we should look for a replacement solution.
- Fixed a bug with the latest version of Chrome (64) that is throwing a security error when we try to check for media queries in the CSS.
- Added a `sleep` to the automated testing because there is a timing problem on CodePen now with iframes.
- Travis CI now requires the '--no-sandbox' flag to be passed to Chrome.
Note that I would have created separate PRs for these, but they all need each other in order for the CI tests to …
> fix: use serve-https github repo instead of the broken npm

- build/bundle.js
- src/project-tests/portfolio-tests.js
CSS `scroll-behavior: smooth` causes navbar link test to fail for the Portfolio tests. The logic was changed to use `setTimeout` so the scrolling has time to complete before checking if the window scrolled.
> fix: scroll-behavior smooth causes navbar link test to fail

- build/bundle.js
- src/index.js
- src/stylesheets/fcc-test-toggler.css
- src/utils/fcc-test-toggler-skeleton.html
Using the localStorage method suggested by @Knochenmark , keep the test window collapsed after the user hides it.
> keep test window hidden after toggle

- build/bundle.js
- src/project-tests/markdown-previewer-tests.js
Added regex to match markdown Setext headings
> Markdown -- Add regex for matching Setext headings

- build/bundle.js
- src/index.js
- src/stylesheets/fcc-test-toggler.css
- src/stylesheets/fcc-test-ui.css
- src/stylesheets/mocha-modal.css
Made sure the most common properties are specified on the parent div for the test UI and then add a CSS rule so that all those properties are inherited by all children elements. This is a little heavy handed and required that we unset or specify those properties in some children elements, but it should go a long way towards making our CSS more specific than an element override in the user CSS.
> fix: make it more difficult for users to override test UI CSS

- build/bundle.js
- package.json
- src/stylesheets/fcc-test-toggler.css
The toggler was looking skewed in Chrome. This adds margins to the middle transform bar and fixes the mistake I made in #274 of aligning the bottom bar using `top` instead of `bottom`, complicating things.
> fix toggler

- build/bundle.js
- src/project-tests/pomodoro-clock-tests.js
The PR required to pass #311 . Call audioElem for each assert in the last audio test as anti-cache strategy.
> call audio element each assert in last test

- .travis.yml
- CONTRIBUTING.md
- config/live-server-https.js.example
- package.json
- test/setup.js.example
- test/setup.js.travis
> revert to live-serve-build

- build/bundle.js
- src/project-tests/drum-machine-tests.js
This PR accommodates all click events with `mousedown`, `click`, and `mouseup` in that order. Additionally, dispatched events on DOM elements (`<audio>`) need to be configured with Object.defineProperties in a similar way to the workaround in markdown-previewer. Before all of the tests, we make the audio object configurable and writable.
> Drum Machine: mousedown-click-mouseup and audio element paused Object.properties

- build/bundle.js
- src/project-tests/markdown-previewer-tests.js
> markdown: allow blockquotes without whitespace after

- build/bundle.js
- src/project-tests/heat-map-tests.js
We were missing a tagName in the querySelector on test nine.
> heatmap qualify .cell className with rect tagName

- .travis.yml
The Travis CI build was crashing on the Personal Portfolio tests with:
```
WebDriverError: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
```
This turned out to be a problem with the size of `/dev/shm`. 
See https://github.com/SeleniumHQ/docker-selenium/issues/431
The fix was to just remount `/dev/shm` with a larger size as part of the Travis setup.
> fix: Travis CI build was crashing due to need for larger /dev/shm

- build/bundle.js
- src/index.js
The localStorage Object for keeping the test window closed was saving the closure function itself and not the intended return value (String). I'm removing the closure and using existing String variables for consistency.
> ensure localStorage key for hidden test-window is a String

- build/bundle.js
- src/project-tests/technical-docs-tests.js
The tests require that the navbar remain positioned in the top-left quadrant of the screen. This update is true to the wording in the user story, accommodating projects with greater offsets on top and left.
> tech-doc_navbar in top-left quadrant

- build/bundle.js
- src/project-tests/portfolio-tests.js
The parameter passed to testScroll is Boolean so removed the function parentheticals
> portfolio nav-link test -- ensure param is Boolean and not a function

- build/bundle.js
- src/stylesheets/mocha-modal.css
The content of the test suite overflows the window when on a smaller sized window (e.g.: mobile). This is simply a css change in the flex implementation.
> fix text content overflowing container

- README.md
Same as PR #319 which is not able to build. Want to see if this will build ok.
> Fix: update docs to use freeCodeCamp CDN.

- .travis.yml
Hopefully this fixes the problem with the Travis build in PR #445.
> Allow sudo in Travis build so we can change the size of shared memory.

- CONTRIBUTING.md
This commit updates the links to the CDNs to the recently relocated paths.
> fix: update paths to build.js CDNs

- README.md
> fix: update path to build.js CDN in README

- CONTRIBUTING.md
- local_test/index.html
- package.json
- webpack.config.dev.js
- yarn.lock
Reverts freeCodeCamp/testable-projects-fcc#549
> Revert "feat: Use webpack-dev-server"

- CONTRIBUTING.md
- package.json
- webpack.config.dev.js
- yarn.lock
> feat: webpack-dev-server is used for develop

- .eslintignore
- .travis.yml
- commitizen.config.js
- commitlint.config.js
- package.json
- yarn.lock
- commitizen friendly repository is made as in the freecodecamp/curriculum
- added lint checks on the commit message
- added lint project checks on the pre-commit hook.
> feat(tools): husky, commitlint and commitizen was added

- src/project-tests/calculator-tests.js
- src/project-tests/pomodoro-clock-tests.js
- src/utils/element-utils.js
> fix: get value from input tag

- src/utils/global-D3-tests.js
- trigger mouseleave event
- getComputedStyle is used to check element is hidden
> fix: tool tip test

- test/alignment-D3.js
Only removing tests preemptively. Other JSDOM test changes will still need to associate with #546
> fix(tests): remove tests in prep for getBoundingClientRect

- .travis.yml
In reference to a discussion related to our current build error, https://github.com/travis-ci/travis-ci/issues/5538#issuecomment-220135972 -- trying the command, `script: ./deploy.sh`
> chore(tools): use current working directory delimiter for ./deploy.sh

- .travis.yml
> chore(tools): use bash instead of sh for pushd and popd

- src/index.js
> fix: position UI at the top layer

- src/project-tests/markdown-previewer-tests.js
> fix: trigger input event on a react element

- .travis.yml
per @ValeraS this should fix the deploy process
> chore(tools): bash deploy.sh without cwd delimiter

- src/project-tests/bar-chart-tests.js
- src/project-tests/calculator-tests.js
- src/project-tests/choropleth-tests.js
- src/project-tests/drum-machine-tests.js
- src/project-tests/heat-map-tests.js
- src/project-tests/markdown-previewer-tests.js
- src/project-tests/pomodoro-clock-tests.js
- src/project-tests/portfolio-tests.js
- src/project-tests/product-landing-page-tests.js
- src/project-tests/quote-machine-tests.js
- src/project-tests/scatter-plot-tests.js
- src/project-tests/survey-form-tests.js
- src/project-tests/technical-docs-tests.js
- src/project-tests/tree-map-tests.js
- src/project-tests/tribute-page-tests.js
- src/utils/global-D3-tests.js
- src/utils/shared-test-strings.js
- Manual line numbering was deleted.
> feat: changed the mocha custom test report

- src/index.js
- src/project-tests/markdown-previewer-tests.js
> fix: load marked for the markdown-previewer test

- package-lock.json
- src/project-tests/technical-docs-tests.js
ISSUES CLOSED: #433
User story wording. The test of navbar position fails if the navbar scrolls with the page, which wasn't clear in the wording.
> fix(scripts): tech-doc clarify navbar position user story

- deploy.sh
In the Travis CI, need to add an environment variable `CDN_REPO_SLUG = freeCodeCamp/cdn.git`
With this PR, we will see a result of a push to CDN repo.
> chore(deploy): change the direct link to the CDN repo to a variable

- .travis.yml
- CONTRIBUTING.md
- package.json
- src/index.js
- test/automate/automate-utils.js
- test/codepen-projects.js
- test/setup.js.example
- test/setup.js.travis
- yarn.lock
- automated testing in Firefox
- headless mode
- muted sounds
> feat: test in Firefox and headless mode

- src/project-tests/tribute-page-tests.js
> fix: test removes inner styles

- src/utils/global-D3-tests.js
> fix: use setTimeout to accommodate tooltip transitions

- src/project-tests/drum-machine-tests.js
> fix: remove redundant setTimeout

- src/project-tests/markdown-previewer-tests.js
> fix: use checks not specific for marked.js

- src/project-tests/pomodoro-clock-tests.js
> feat: use async for pomodoro tests

- src/project-tests/pomodoro-clock-tests.js
> fix: simplify regex for a pomodoro timer

- src/stylesheets/default.css
Corrected spelling in first comment block of "therefor" to "therefore".
Corrected grammar in third comment block from "This rules..." to "These rules..."
- [x ] Your pull request targets the `master` branch of freeCodeCamp/testable-projects-fcc
- [x ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ x] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [x ] Working changes have been added to the build by running `npm run build`
> Corrected spelling/grammar in comment blocks

- src/project-tests/markdown-previewer-tests.js
- src/utils/element-utils.js
> fix: decode text when collecting headers

- src/utils/global-D3-tests.js
> fix: check dynamically added tooltip

- src/project-tests/technical-docs-tests.js
> fix: not found corresponding header for .nav-link

- src/project-tests/portfolio-tests.js
> fix: porfolio welcome section layout test

- .travis.yml
- test/automate/automate-utils.js
> fix(tests): according to CodePen changes

- src/project-tests/survey-form-tests.js
> fix: invalid query selector

- src/project-tests/pomodoro-clock-tests.js
> fix: wait for timer a required time in Pomodoro tests

- src/project-tests/portfolio-tests.js
> fix: Cannot read property substr of null

- src/project-tests/drum-machine-tests.js
> fix: trigger keyup event

- webpack.config.js
> fix: output path in a development mode

- src/utils/global-D3-tests.js
> fix: always try to clear out a tooltip

- .eslintrc
> chore(tools): prevent ESLint from looking for config outside the project

- src/project-tests/survey-form-tests.js
> fix(tests): mention value attr in radio button user story

- src/index.js
- src/project-tests/tribute-page-tests.js
> fix: add missing spaces between words

- .github/PULL_REQUEST_TEMPLATE.md
> fix: broken link

- src/project-tests/technical-docs-tests.js
> fix(tests): user story wording

- src/project-tests/portfolio-tests.js
- src/project-tests/product-landing-page-tests.js
- src/project-tests/technical-docs-tests.js
- src/utils/style-sheet-utils.js
> fix: take into account CSS Supports rules

- src/project-tests/technical-docs-tests.js
This PR reflects changes made to the fCC page of these tests over here https://github.com/freeCodeCamp/freeCodeCamp/pull/35183/commits/a32f2da271c08b0d2b7c2b6abfbffbc865cd74b8
> Change Javascript to JavaScript to reflect changes on the monorepo

- src/project-tests/markdown-previewer-tests.js
> fix: ignore trailing new line in markdown previewer tests

- src/utils/fcc-test-suite-skeleton.html
Added `rel="noopener"` attribute to 'Report Bug' link in the file `src/utils/fcc-test-suite-skeleton.html` so that they pass 'Best Practices' audits. Without the attribute, audits suggest that the links to cross origin destinations are unsafe.
Changes made -
```
<span id="fcc_report-bug"><a
href="https://github.com/freeCodeCamp/testable-projects-fcc/issues/new"
target="_blank" rel="noopener">Report Bug</a>
</span>
```
> Added rel=noopener attribute to 'Report Bug' link to fix failing best practices audit

- src/stylesheets/fcc-test-ui.css
Changed background-color property for test suite buttons in file `src/stylesheets/fcc-test-ui.css` so that they pass accessibility audits.
Previously - 
```
button.fcc_foldout_button {
background-color: rgba(128, 128, 128, 0.7);
color: white;
}
```
Fix - 
```
// this is the suggested fix
button.fcc_foldout_button {
background-color: rgba(50, 50, 50, 0.75);
color: white;
}
```
> fix: styles - test buttons insufficient contrast ratio failing accessibility audits

- src/projects/tribute-page/index.html
- [] Your changes have been tested either locally or using a newly created CDN based on your fork's testable-projects-fcc/build/bundle.js file
- [] Working changes have been added to the build by running `npm run build`
This PR fixes the image caption making it the same as the now updated Codepen. We should get this merged to make sure the repo version and Codepen version are the same.
> fix(project): correct image caption

- src/utils/fcc-test-suite-skeleton.html
The PR adds a link to the forum so that users can have the proper place to report for help and reduce the high workload on the test repo
> feat: 🎸 Added forum link

- src/project-tests/calculator-tests.js
- src/projects/javascript-calculator/index.jsx
ISSUES CLOSED: #908
@scissorsneedfoodtoo Once this is merged, the javascript calculator Codepen will need to be updated as well. Thank you. :)
> fix(tests): except minus operator intended as negative sign

- .travis.yml
- test/automate/automate-utils.js
- test/projects.js
It's how test errors will be shown:
> feat(ci): show extended error information

- src/projects/survey-form/index.css
- src/projects/survey-form/index.html
- src/projects/survey-form/index.js
Here is my first go at the new survey form. Any corrections or suggestions are welcome.
> feat: new survey form

- src/projects/javascript-calculator/index.jsx
This pull request contains two changes to the JavaScript Calculator project. They allow the first operand of a formula to be a zero, for example 0+1, but prevent it from having a zero followed by a digit.
The first change on line 117 adds a check for an empty formula when the zero (0) button is pressed. This change allows a leading zero to be added to the formula. 
This change however introduces an issue that allows for the formula to start with a zero followed by a digit, for example 02. The change to line 118 addresses this by adding an additional check into the regex expression to catch formulas that begin with a zero. The following line which is unchanged replaces the zero with a new value.
> fix: allow zero as first operand for JavaScript project

- src/project-tests/product-landing-page-tests.js
Based on the discussion in [this closed issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38112#issuecomment-579266829), this PR clarifies the user story no. 12, so that it is clearer that `email-submit` is not an endpoint.
**Note:** This PR should be merged at the same time that [this PR is merged in the freeCodeCamp repo](https://github.com/freeCodeCamp/freeCodeCamp/pull/38127)
> fix: removed part of user story no. 12 for the Build a Product Landing Page project

- src/project-tests/pomodoro-clock-tests.js
Reverts freeCodeCamp/testable-projects-fcc#1056
> Revert "feat: Add test to pomodoro-clock-tests"

- src/projects/d3-scatter-plot/index.js
The issue above pointed out that the legend elements in the scatter plot graph both have the id `legend`. The example in the project still passes the tests, but the contributor in that issue thought it would be best if we used best practices and only have one id named `legend`.
This is a simple fix that creates a container with the `legend` id, and appends the legend labels inside. Not sure if this is the best way to do that in d3, so please let me know if there's a better way.
Here's the code up on CodePen for verification: https://codepen.io/scissorsneedfoodtoo/pen/XWmreBv
> fix: unique id for scatterplot legend

- src/projects/d3-scatter-plot/index.js
Adding a line that I forgot to include in my last PR, https://github.com/freeCodeCamp/testable-projects-fcc/pull/1082 :sweat_smile:. This should complete the fix.
> fix: scatterplot legend forgotten line

- src/project-tests/pomodoro-clock-tests.js
Adds `await timerStateChange()` when increment button pressed for `I can see an element with corresponding id="time-left".` test.  
Closes #1069
> fix: add await for timer state to change

- src/index.js
This PR implements a check for access to localStorage and an alert message if access to localStorage is blocked. It is just a try/catch which is what Modernizr does for [testing localstorage support](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/storage/localstorage.js).
Here is a test page that show the alert. Block third-party cookies in the browser to see the alert.
https://codepen.io/lasjorg/pen/JjYbvxz
> fix: Add check for localStorage support in browser

- src/index.js
After updating to Mocha 7.2.0 the test suite can only be run one time and will error out on subsequent runs. See the related issue for more information.
Adding `mocha.cleanReferencesAfterRun(false);` to the setup fixes this.
I'm not sure if there are any potential issues with this approach (like leaking if not manually disposing of the instance) so if anyone has some input on this I'd appreciate it.
> fix: run cleanReferencesAfterRun(false) in setup

- src/project-tests/25-5-clock-tests.js
> fix: minor typo I noticed

- src/projects/markdown-previewer/index.jsx
Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/35615
> fix: invalid markdown syntax

- src/utils/fcc-test-suite-skeleton.html
Changes bug report link to main repo
Updates the "Report Bug" link to take campers to the freeCodeCamp repository.
> fix: update bug report link

- src/stylesheets/fcc-test-ui.css
- src/utils/fcc-test-suite-skeleton.html
Removes the `Report Bug` link and centres the `Ask for Help` link:
> fix: remove bug report link

- src/projects/25-5-clock/index.scss
The 25+5 project was not loading or loading very slowly. I commented this code out on codepen as a temporary fix. It seemed to fix the issue. So this PR removes that code. When it's merged, the codepen can be updated to remove the code I commented out.
> fix: 25+5 project not loading issue

- src/projects/javascript-calculator/index.jsx
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/37942
I fixed up the codepen, moved the javascript from there to this PR, then copied the html, css, and javascript from here back to the pen to test it. It passed. Perhaps not the best code, but it was a quick fix, and it appears to be working.
The linter automatically changed the single quotes to double.
> fix: update calculator code to fix issue

- src/projects/random-quote-machine/index.html
Related to:
https://github.com/freeCodeCamp/freeCodeCamp/issues/40089
https://github.com/freeCodeCamp/freeCodeCamp/pull/40118
> feat: change to target=top on quote machine tweet btn

- src/projects/technical-documentation-page/index.css
> fix: change white-space to pre-line

- src/projects/portfolio/index.html
- src/projects/product-landing-page/index.html
- src/projects/tribute-page/index.html
Update image links to use CDN as per issue https://github.com/freeCodeCamp/freeCodeCamp/issues/41913
After this gets merged someone with access to the fCC Codepen will have to update the respective Codepens as well.
> fix: use cdn for images

- src/index.js
Changes the test runner summary button label from "Tests passed/total" to "passed/total Passed" to fix usability issue described in #1142
> fix: test button label usability issue
